// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback matches the default in lib/prisma.ts so CLI commands work
    // even when .env is not explicitly loaded (Prisma 7 reads this at runtime).
    url: process.env["DATABASE_URL"] ?? "file:./prisma/dev.db",
  },
});
