// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For local dev: file:./prisma/dev.db (no auth needed)
    // For Turso: libsql://... — TURSO_AUTH_TOKEN env var is read automatically by libsql
    url:
      process.env["DATABASE_URL"] ??
      "libsql://avora-db-nader-alawadi.aws-eu-west-1.turso.io",
  },
});
