"use client";

import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import { motion, AnimatePresence, useInView } from "framer-motion";
import { AvoraLogo } from "@/components/ui/AvoraLogo";

// ─── Particles ───────────────────────────────────────────────────────────────
const particles = Array.from({ length: 20 }, (_, i) => ({
  id: i,
  x: (i * 37 + 13) % 100,
  y: (i * 53 + 7) % 100,
  size: (i % 3) + 2,
}));

// ─── CountUp Component ────────────────────────────────────────────────────────
function CountUp({ target, suffix = "" }: { target: number; suffix?: string }) {
  const [count, setCount] = useState(0);
  const ref = useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { once: true });

  useEffect(() => {
    if (!inView) return;
    let start = 0;
    const duration = 2000;
    const increment = target / (duration / 16);
    const timer = setInterval(() => {
      start += increment;
      if (start >= target) {
        setCount(target);
        clearInterval(timer);
      } else {
        setCount(Math.floor(start));
      }
    }, 16);
    return () => clearInterval(timer);
  }, [inView, target]);

  return (
    <span ref={ref}>
      {count}
      {suffix}
    </span>
  );
}

// ─── Nav Link with animated underline ─────────────────────────────────────────
function NavLink({
  href,
  children,
  scrolled,
}: {
  href: string;
  children: React.ReactNode;
  scrolled: boolean;
}) {
  return (
    <Link
      href={href}
      className="relative text-sm font-medium transition-colors duration-200 group"
      style={{ color: scrolled ? "#475569" : "rgba(255,255,255,0.85)" }}
    >
      {children}
      <span
        style={{
          position: "absolute",
          bottom: -2,
          left: 0,
          height: 2,
          width: 0,
          background: "#14B8A6",
          borderRadius: 2,
          transition: "width 0.3s ease",
        }}
        className="group-hover:w-full"
      />
    </Link>
  );
}

// ─── Feature Cards ────────────────────────────────────────────────────────────
const featureCardVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0 },
};

const features = [
  {
    icon: "🎯",
    title: "AI-Powered ICP Builder",
    desc: "Define your ideal customer profile with AI in minutes. ARIA analyzes your business and builds a precision ICP.",
  },
  {
    icon: "🔍",
    title: "Smart Lead Discovery",
    desc: "Find verified decision-makers across 150+ countries with 94% email accuracy guaranteed.",
  },
  {
    icon: "📊",
    title: "GTM Strategy Engine",
    desc: "Get a complete go-to-market playbook tailored to your business, generated by AI in seconds.",
  },
  {
    icon: "🤖",
    title: "ARIA AI Assistant",
    desc: "Your personal AI sales coach guides you every step of the way — from ICP to closed deal.",
  },
  {
    icon: "📈",
    title: "ABM Campaign Builder",
    desc: "Target accounts with precision using AI-driven insights and automated multi-channel outreach.",
  },
  {
    icon: "🔗",
    title: "CRM Auto-Sync",
    desc: "Leads flow directly into your pipeline, enriched and ready to close. Works with HubSpot, Salesforce & more.",
  },
];

// ─── Integrations ─────────────────────────────────────────────────────────────
const integrations = [
  { name: "HubSpot", color: "#FF7A59", letter: "H" },
  { name: "Salesforce", color: "#00A1E0", letter: "S" },
  { name: "LinkedIn", color: "#0A66C2", letter: "in" },
  { name: "WhatsApp", color: "#25D366", letter: "W" },
  { name: "Slack", color: "#4A154B", letter: "S" },
  { name: "Gmail", color: "#EA4335", letter: "G" },
  { name: "Zapier", color: "#FF4A00", letter: "Z" },
  { name: "Pipedrive", color: "#1A6B3C", letter: "P" },
  { name: "Notion", color: "#1A1A1A", letter: "N" },
  { name: "Stripe", color: "#635BFF", letter: "S" },
];

// ─── Testimonials ─────────────────────────────────────────────────────────────
const testimonials = [
  {
    name: "John Smith",
    role: "VP Sales",
    company: "TechCorp",
    initial: "J",
    color: "#14B8A6",
    quote:
      "AVORA cut our sales cycle in half. The AI-generated leads are incredibly accurate — 90% conversion to meetings.",
  },
  {
    name: "Sarah Chen",
    role: "Growth Lead",
    company: "StartupXYZ",
    initial: "S",
    color: "#F97316",
    quote:
      "The GTM strategy ARIA generated for us was more detailed than anything our consultants produced. Game-changer.",
  },
  {
    name: "Ahmed Hassan",
    role: "CEO",
    company: "ScaleUp MENA",
    initial: "A",
    color: "#8B5CF6",
    quote:
      "Finally a platform that understands B2B sales in the Arab world. The Arabic support is flawless.",
  },
];

// ─── Pricing plans ────────────────────────────────────────────────────────────
const pricingPlans = [
  {
    name: "Starter",
    price: 0 as number | null,
    for: "Small teams just getting started",
    cta: "Start Free",
    ctaVariant: "outline-teal",
    href: "/register",
    features: [
      "5 Free Leads/month",
      "Basic ICP Builder",
      "ARIA AI Chat (limited)",
      "1 GTM Report/month",
      "Email Support",
    ],
    highlight: false,
    badge: null as string | null,
  },
  {
    name: "Growth",
    price: 149 as number | null,
    for: "Growing sales teams",
    cta: "Start Growth",
    ctaVariant: "coral",
    href: "/register?plan=growth",
    features: [
      "50 Leads/month",
      "Advanced ICP + ABM",
      "Full ARIA AI Assistant",
      "5 GTM Reports/month",
      "CRM Auto-Sync",
      "Priority Support",
    ],
    highlight: true,
    badge: "Most Popular",
  },
  {
    name: "Enterprise",
    price: null as number | null,
    for: "Large organizations",
    cta: "Contact Sales",
    ctaVariant: "navy",
    href: "/contact",
    features: [
      "Unlimited Leads",
      "Custom ICP Models",
      "Dedicated ARIA Instance",
      "Unlimited Reports",
      "Custom Integrations",
      "24/7 SLA Support",
      "Custom Contracts",
    ],
    highlight: false,
    badge: null as string | null,
  },
];

// ─── Footer columns ────────────────────────────────────────────────────────────
const footerColumns = [
  {
    title: "Product",
    links: ["Features", "ICP Builder", "Lead Discovery", "GTM Strategy", "ARIA AI", "Pricing"],
  },
  {
    title: "Solutions",
    links: ["Sales Teams", "Growth Teams", "Founders", "Enterprise", "Agencies"],
  },
  {
    title: "Company",
    links: ["About", "Careers", "Blog", "Press", "Contact"],
  },
  {
    title: "Legal",
    links: ["Privacy Policy", "Terms of Service", "GDPR", "Security"],
  },
];

// ─── Main Page ─────────────────────────────────────────────────────────────────
export default function LandingPage() {
  const [scrolled, setScrolled] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [isRTL, setIsRTL] = useState(false);
  const [annual, setAnnual] = useState(false);

  useEffect(() => {
    setIsRTL(navigator.language.startsWith("ar"));
  }, []);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <div dir={isRTL ? "rtl" : "ltr"} style={{ minHeight: "100vh", overflowX: "hidden", fontFamily: "Inter, Nunito, sans-serif" }}>

      {/* ── GLOBAL STYLES ─────────────────────────────────────── */}
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
        @keyframes gradientShift {
          0%   { background-position: 0% 50%; }
          50%  { background-position: 100% 50%; }
          100% { background-position: 0% 50%; }
        }
        @keyframes marquee {
          0%   { transform: translateX(0); }
          100% { transform: translateX(-50%); }
        }
        .marquee-track { animation: marquee 22s linear infinite; }
        .nav-link-underline { position: absolute; bottom: -2px; left: 0; height: 2px; width: 0; background: #14B8A6; border-radius: 2px; transition: width 0.3s ease; }
        a:hover .nav-link-underline { width: 100%; }
      `}</style>

      {/* ══════════════════════════════════════════════════════════
          1. STICKY NAVIGATION
      ══════════════════════════════════════════════════════════ */}
      <header
        style={{
          position: "sticky",
          top: 0,
          zIndex: 50,
          background: scrolled ? "rgba(255,255,255,0.95)" : "transparent",
          backdropFilter: scrolled ? "blur(12px)" : "none",
          WebkitBackdropFilter: scrolled ? "blur(12px)" : "none",
          boxShadow: scrolled ? "0 1px 24px rgba(0,0,0,0.08)" : "none",
          transition: "background 0.3s, box-shadow 0.3s",
        }}
      >
        <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 24px" }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", height: 64 }}>
            {/* Logo */}
            <Link href="/" style={{ display: "flex", alignItems: "center", textDecoration: "none", flexShrink: 0 }}>
              <AvoraLogo variant={scrolled ? "dark" : "light"} height={32} />
            </Link>

            {/* Desktop Nav */}
            <nav style={{ display: "flex", alignItems: "center", gap: 32 }} className="hidden md:flex">
              {["Product", "Solutions", "Pricing", "Resources", "Customers"].map((item) => (
                <NavLink key={item} href={`#${item.toLowerCase()}`} scrolled={scrolled}>
                  {item}
                </NavLink>
              ))}
            </nav>

            {/* Desktop CTAs */}
            <div style={{ display: "flex", alignItems: "center", gap: 12 }} className="hidden md:flex">
              <Link
                href="/login"
                style={{
                  fontSize: 14,
                  fontWeight: 500,
                  padding: "8px 16px",
                  borderRadius: 10,
                  border: scrolled ? "1px solid #E2E8F0" : "1px solid rgba(255,255,255,0.3)",
                  color: scrolled ? "#475569" : "white",
                  textDecoration: "none",
                  transition: "all 0.2s",
                }}
              >
                Sign In
              </Link>
              <Link
                href="/register"
                style={{
                  fontSize: 14,
                  fontWeight: 600,
                  padding: "8px 20px",
                  borderRadius: 10,
                  background: "#F97316",
                  color: "white",
                  textDecoration: "none",
                  transition: "all 0.2s",
                  boxShadow: "0 4px 16px rgba(249,115,22,0.35)",
                }}
              >
                Start Free
              </Link>
            </div>

            {/* Mobile hamburger */}
            <button
              onClick={() => setMobileOpen(!mobileOpen)}
              aria-label="Toggle navigation"
              style={{ background: "none", border: "none", cursor: "pointer", padding: 8, display: "flex", flexDirection: "column", gap: 5 }}
              className="md:hidden"
            >
              {[0, 1, 2].map((n) => (
                <span
                  key={n}
                  style={{
                    display: "block",
                    width: 24,
                    height: 2,
                    borderRadius: 2,
                    background: scrolled ? "#0A1628" : "white",
                    transition: "all 0.3s",
                    transform:
                      n === 0 && mobileOpen
                        ? "rotate(45deg) translate(5px, 5px)"
                        : n === 2 && mobileOpen
                        ? "rotate(-45deg) translate(5px, -5px)"
                        : "none",
                    opacity: n === 1 && mobileOpen ? 0 : 1,
                  }}
                />
              ))}
            </button>
          </div>
        </div>

        {/* Mobile Menu */}
        <AnimatePresence>
          {mobileOpen && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
              transition={{ duration: 0.25 }}
              style={{ background: "white", borderTop: "1px solid #E2E8F0", overflow: "hidden" }}
              className="md:hidden"
            >
              <div style={{ padding: "24px" }}>
                {["Product", "Solutions", "Pricing", "Resources", "Customers"].map((item, i) => (
                  <motion.div
                    key={item}
                    initial={{ opacity: 0, x: -16 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.06 }}
                  >
                    <Link
                      href={`#${item.toLowerCase()}`}
                      onClick={() => setMobileOpen(false)}
                      style={{
                        display: "block",
                        padding: "12px 0",
                        fontSize: 16,
                        fontWeight: 500,
                        color: "#0A1628",
                        textDecoration: "none",
                        borderBottom: "1px solid #F1F5F9",
                      }}
                    >
                      {item}
                    </Link>
                  </motion.div>
                ))}
                <div style={{ marginTop: 20, display: "flex", flexDirection: "column", gap: 10 }}>
                  <Link href="/login" style={{ textAlign: "center", padding: "12px", border: "1px solid #E2E8F0", borderRadius: 12, color: "#475569", textDecoration: "none", fontWeight: 500 }}>
                    Sign In
                  </Link>
                  <Link href="/register" style={{ textAlign: "center", padding: "12px", background: "#F97316", borderRadius: 12, color: "white", textDecoration: "none", fontWeight: 600 }}>
                    Start Free
                  </Link>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </header>

      {/* ══════════════════════════════════════════════════════════
          2. HERO SECTION
      ══════════════════════════════════════════════════════════ */}
      <section
        id="product"
        style={{
          background: "linear-gradient(135deg, #0A1628 0%, #0D3D3D 50%, #0A1628 100%)",
          position: "relative",
          overflow: "hidden",
          paddingTop: "6rem",
          paddingBottom: "6rem",
        }}
      >
        {/* Orb 1 — teal top-left */}
        <motion.div
          animate={{ y: [-30, 30, -30], rotate: [0, 5, 0] }}
          transition={{ duration: 8, repeat: Infinity, ease: "easeInOut", delay: 0 }}
          style={{
            position: "absolute",
            top: -100,
            left: -100,
            width: 500,
            height: 500,
            borderRadius: "50%",
            background: "radial-gradient(circle, #14B8A6, transparent 70%)",
            opacity: 0.15,
            pointerEvents: "none",
          }}
        />
        {/* Orb 2 — coral bottom-right */}
        <motion.div
          animate={{ y: [-30, 30, -30], rotate: [0, -5, 0] }}
          transition={{ duration: 10, repeat: Infinity, ease: "easeInOut", delay: 2 }}
          style={{
            position: "absolute",
            bottom: -80,
            right: -80,
            width: 400,
            height: 400,
            borderRadius: "50%",
            background: "radial-gradient(circle, #F97316, transparent 70%)",
            opacity: 0.1,
            pointerEvents: "none",
          }}
        />
        {/* Orb 3 — purple top-right */}
        <motion.div
          animate={{ y: [-20, 20, -20], rotate: [0, 8, 0] }}
          transition={{ duration: 7, repeat: Infinity, ease: "easeInOut", delay: 1 }}
          style={{
            position: "absolute",
            top: "10%",
            right: "5%",
            width: 300,
            height: 300,
            borderRadius: "50%",
            background: "radial-gradient(circle, #8B5CF6, transparent 70%)",
            opacity: 0.1,
            pointerEvents: "none",
          }}
        />

        {/* Particles */}
        {particles.map((p) => (
          <div
            key={p.id}
            style={{
              position: "absolute",
              left: `${p.x}%`,
              top: `${p.y}%`,
              width: p.size,
              height: p.size,
              borderRadius: "50%",
              background: "white",
              opacity: 0.3,
              pointerEvents: "none",
            }}
          />
        ))}

        <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 24px", position: "relative", zIndex: 10 }}>

          {/* Headline */}
          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.7 }}
            style={{
              textAlign: "center",
              fontWeight: 800,
              color: "white",
              lineHeight: 1.1,
              fontSize: "clamp(36px, 5vw, 64px)",
              maxWidth: 820,
              margin: "0 auto",
              fontFamily: "Inter, sans-serif",
            }}
          >
            Find Your Next Customer{" "}
            <span style={{ color: "#14B8A6" }}>Before They Find You</span>
          </motion.h1>

          {/* Subheadline */}
          <motion.p
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5, duration: 0.6 }}
            style={{
              textAlign: "center",
              fontSize: 20,
              color: "#94A3B8",
              maxWidth: 600,
              margin: "24px auto 0",
              lineHeight: 1.6,
            }}
          >
            AVORA&apos;s AI identifies, qualifies, and connects you with decision-makers — automatically.
          </motion.p>

          {/* CTAs */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.7, duration: 0.5 }}
            style={{ display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "center", gap: 16, marginTop: 40 }}
          >
            <Link
              href="/register"
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: 8,
                background: "#F97316",
                color: "white",
                fontWeight: 700,
                fontSize: 16,
                padding: "0 32px",
                height: 56,
                borderRadius: 12,
                textDecoration: "none",
                boxShadow: "0 8px 32px rgba(249,115,22,0.4)",
                transition: "transform 0.2s, box-shadow 0.2s",
              }}
            >
              Start for Free →
            </Link>
            <button
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: 8,
                background: "transparent",
                color: "white",
                fontWeight: 600,
                fontSize: 16,
                padding: "0 32px",
                height: 56,
                borderRadius: 12,
                border: "2px solid rgba(255,255,255,0.35)",
                cursor: "pointer",
                transition: "background 0.2s",
              }}
            >
              <span style={{ fontSize: 13 }}>▶</span> Watch Demo
            </button>
          </motion.div>

          {/* Social Proof */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.9, duration: 0.6 }}
            style={{ marginTop: 40, textAlign: "center" }}
          >
            <p style={{ fontSize: 13, color: "#64748B", marginBottom: 16 }}>
              Trusted by 2,000+ sales teams worldwide
            </p>
            <div style={{ overflow: "hidden", maxWidth: 640, margin: "0 auto" }}>
              <div className="marquee-track" style={{ display: "flex", gap: 16, width: "max-content" }}>
                {[
                  { name: "HubSpot", color: "#FF7A59" },
                  { name: "Salesforce", color: "#00A1E0" },
                  { name: "Stripe", color: "#635BFF" },
                  { name: "Notion", color: "#94A3B8" },
                  { name: "Slack", color: "#4A154B" },
                  { name: "HubSpot", color: "#FF7A59" },
                  { name: "Salesforce", color: "#00A1E0" },
                  { name: "Stripe", color: "#635BFF" },
                  { name: "Notion", color: "#94A3B8" },
                  { name: "Slack", color: "#4A154B" },
                ].map((logo, i) => (
                  <div
                    key={i}
                    style={{
                      height: 34,
                      padding: "0 18px",
                      borderRadius: 8,
                      background: logo.color + "18",
                      border: `1px solid ${logo.color}33`,
                      display: "flex",
                      alignItems: "center",
                      flexShrink: 0,
                    }}
                  >
                    <span style={{ color: logo.color, fontSize: 12, fontWeight: 700 }}>{logo.name}</span>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>

          {/* Product Mockup */}
          <motion.div
            initial={{ opacity: 0, y: 60 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.9, duration: 0.8 }}
            whileHover={{ y: -8, transition: { duration: 0.3 } }}
            style={{ maxWidth: 800, margin: "64px auto 0", transform: "rotate(1.5deg)" }}
          >
            <div
              style={{
                background: "#0F1F3D",
                borderRadius: 16,
                overflow: "hidden",
                boxShadow: "0 40px 120px rgba(0,0,0,0.55), 0 0 0 1px rgba(255,255,255,0.07)",
                position: "relative",
              }}
            >
              {/* Window chrome */}
              <div
                style={{
                  background: "#1A2E4A",
                  padding: "12px 16px",
                  display: "flex",
                  alignItems: "center",
                  gap: 8,
                  borderBottom: "1px solid rgba(255,255,255,0.06)",
                }}
              >
                <div style={{ width: 12, height: 12, borderRadius: "50%", background: "#FF5F57" }} />
                <div style={{ width: 12, height: 12, borderRadius: "50%", background: "#FFBD2E" }} />
                <div style={{ width: 12, height: 12, borderRadius: "50%", background: "#28C840" }} />
                <div style={{ marginLeft: 16, flex: 1, height: 20, background: "rgba(255,255,255,0.06)", borderRadius: 4, maxWidth: 320 }} />
              </div>

              {/* App layout */}
              <div style={{ display: "flex", minHeight: 370 }}>
                {/* Sidebar */}
                <div style={{ width: 180, background: "#0D1A30", padding: 16, borderRight: "1px solid rgba(255,255,255,0.05)", flexShrink: 0 }}>
                  <div style={{ height: 28, background: "rgba(20,184,166,0.2)", borderRadius: 6, marginBottom: 10, border: "1px solid rgba(20,184,166,0.3)" }} />
                  {[1, 2, 3, 4, 5].map((n) => (
                    <div key={n} style={{ height: 24, background: "rgba(255,255,255,0.05)", borderRadius: 6, marginBottom: 6 }} />
                  ))}
                  <div style={{ marginTop: 20, height: 1, background: "rgba(255,255,255,0.05)" }} />
                  {[1, 2].map((n) => (
                    <div key={n} style={{ height: 24, background: "rgba(255,255,255,0.04)", borderRadius: 6, marginTop: 8 }} />
                  ))}
                </div>

                {/* Main */}
                <div style={{ flex: 1, padding: 20 }}>
                  {/* Stats grid */}
                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12, marginBottom: 18 }}>
                    {[
                      { color: "#14B8A6", label: "Leads Found", val: "1,284" },
                      { color: "#F97316", label: "Open Rate", val: "38%" },
                      { color: "#8B5CF6", label: "Meetings", val: "94" },
                    ].map((s) => (
                      <div
                        key={s.label}
                        style={{
                          background: s.color + "18",
                          borderRadius: 10,
                          padding: "12px 14px",
                          border: `1px solid ${s.color}30`,
                        }}
                      >
                        <div style={{ fontSize: 20, fontWeight: 800, color: s.color }}>{s.val}</div>
                        <div style={{ fontSize: 10, color: "rgba(255,255,255,0.4)", marginTop: 2 }}>{s.label}</div>
                      </div>
                    ))}
                  </div>

                  {/* Lead rows */}
                  {[
                    { name: "Alex Morgan", title: "VP Sales · Acme Corp", color: "#14B8A6" },
                    { name: "Priya Nair", title: "Growth Lead · ScaleIO", color: "#F97316" },
                    { name: "James Liu", title: "CEO · Ventures Co", color: "#8B5CF6" },
                    { name: "Fatima Al-Rashid", title: "Head of BD · MENA Tech", color: "#10B981" },
                  ].map((lead) => (
                    <div
                      key={lead.name}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: 10,
                        padding: "9px 0",
                        borderBottom: "1px solid rgba(255,255,255,0.05)",
                      }}
                    >
                      <div
                        style={{
                          width: 32,
                          height: 32,
                          borderRadius: "50%",
                          background: lead.color,
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          fontSize: 12,
                          fontWeight: 700,
                          color: "white",
                          flexShrink: 0,
                        }}
                      >
                        {lead.name[0]}
                      </div>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 13, fontWeight: 600, color: "white" }}>{lead.name}</div>
                        <div style={{ fontSize: 11, color: "rgba(255,255,255,0.38)" }}>{lead.title}</div>
                      </div>
                      <div
                        style={{
                          background: "#14B8A618",
                          border: "1px solid #14B8A635",
                          borderRadius: 20,
                          padding: "2px 8px",
                          fontSize: 10,
                          color: "#14B8A6",
                          fontWeight: 600,
                          flexShrink: 0,
                        }}
                      >
                        ICP ✓
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Floating accuracy badge */}
              <div
                style={{
                  position: "absolute",
                  bottom: 16,
                  right: 16,
                  background: "linear-gradient(135deg, #14B8A6, #0D9488)",
                  borderRadius: 10,
                  padding: "8px 14px",
                  color: "white",
                  fontSize: 13,
                  fontWeight: 700,
                  boxShadow: "0 8px 24px rgba(20,184,166,0.45)",
                }}
              >
                94% Accuracy ✓
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          3. STATS BAR
      ══════════════════════════════════════════════════════════ */}
      <section style={{ background: "#0D3D3D", padding: "4rem 0" }}>
        <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 24px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "2rem 1rem" }} className="md:grid-cols-4">
            {[
              { target: 2, suffix: "M+", label: "Verified Contacts" },
              { target: 94, suffix: "%", label: "Email Accuracy" },
              { target: 3, suffix: "x", label: "Pipeline Growth" },
              { target: 150, suffix: "+", label: "Countries" },
            ].map((stat, i) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1, duration: 0.5 }}
                style={{ textAlign: "center" }}
              >
                <div
                  style={{
                    fontSize: 48,
                    fontWeight: 800,
                    color: "white",
                    lineHeight: 1,
                    fontFamily: "Inter, sans-serif",
                  }}
                >
                  <CountUp target={stat.target} suffix={stat.suffix} />
                </div>
                <div style={{ marginTop: 8, fontSize: 14, fontWeight: 500, color: "#5EEAD4" }}>
                  {stat.label}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          4. FEATURES SECTION
      ══════════════════════════════════════════════════════════ */}
      <section id="solutions" style={{ background: "white", padding: "6rem 0" }}>
        <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 24px" }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            style={{ textAlign: "center", marginBottom: 60 }}
          >
            <h2 style={{ fontSize: "clamp(28px, 3vw, 36px)", fontWeight: 800, color: "#0F172A", margin: 0 }}>
              Everything You Need to Close More Deals
            </h2>
            <p style={{ fontSize: 18, color: "#64748B", maxWidth: 560, margin: "16px auto 0", lineHeight: 1.6 }}>
              The complete GTM intelligence platform trusted by 2,000+ sales teams
            </p>
          </motion.div>

          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={{ hidden: {}, visible: { transition: { staggerChildren: 0.1 } } }}
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(1, 1fr)",
              gap: 24,
            }}
            className="sm:grid-cols-2 lg:grid-cols-3"
          >
            {features.map((f) => (
              <motion.div
                key={f.title}
                variants={featureCardVariants}
                whileHover={{ y: -6, boxShadow: "0 20px 60px rgba(0,0,0,0.12)" }}
                transition={{ duration: 0.25 }}
                style={{
                  background: "white",
                  borderRadius: 12,
                  border: "1px solid #E2E8F0",
                  padding: "32px",
                  cursor: "pointer",
                  boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
                }}
              >
                <div
                  style={{
                    width: 56,
                    height: 56,
                    borderRadius: "50%",
                    background: "linear-gradient(135deg, #14B8A6, #F97316)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    fontSize: 26,
                    marginBottom: 20,
                  }}
                >
                  {f.icon}
                </div>
                <h3 style={{ fontSize: 18, fontWeight: 700, color: "#0F172A", margin: "0 0 10px 0" }}>{f.title}</h3>
                <p style={{ fontSize: 15, color: "#64748B", lineHeight: 1.65, margin: "0 0 16px 0" }}>{f.desc}</p>
                <span style={{ fontSize: 14, fontWeight: 600, color: "#14B8A6" }}>Learn more →</span>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          5. HOW IT WORKS
      ══════════════════════════════════════════════════════════ */}
      <section style={{ background: "#F8FAFC", padding: "6rem 0" }}>
        <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 24px" }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            style={{ textAlign: "center", marginBottom: 80 }}
          >
            <h2 style={{ fontSize: "clamp(28px, 3vw, 36px)", fontWeight: 800, color: "#0F172A", margin: 0 }}>
              From Sign Up to First Deal in 24 Hours
            </h2>
          </motion.div>

          {/* Step 1 */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: 48, alignItems: "center", marginBottom: 96 }} className="lg:grid-cols-2">
            <motion.div
              initial={{ opacity: 0, x: -40 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <div style={{ display: "inline-block", background: "linear-gradient(135deg, #14B8A6, #0D9488)", borderRadius: 8, padding: "4px 14px", fontSize: 12, fontWeight: 700, color: "white", marginBottom: 18, letterSpacing: "0.04em" }}>
                Step 01
              </div>
              <h3 style={{ fontSize: 28, fontWeight: 800, color: "#0F172A", margin: "0 0 14px 0" }}>Connect Your Website</h3>
              <p style={{ fontSize: 17, color: "#64748B", lineHeight: 1.7, margin: 0 }}>
                Sign up in 30 seconds. ARIA instantly analyzes your website to understand your business and ICP.
              </p>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 40 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <div style={{ background: "#0F1F3D", borderRadius: 16, padding: 28, boxShadow: "0 20px 60px rgba(0,0,0,0.15)" }}>
                <div style={{ display: "flex", gap: 10, marginBottom: 20 }}>
                  <div style={{ flex: 1, height: 42, background: "rgba(255,255,255,0.07)", borderRadius: 8, display: "flex", alignItems: "center", paddingLeft: 14 }}>
                    <span style={{ color: "rgba(255,255,255,0.3)", fontSize: 13 }}>https://yourcompany.com</span>
                  </div>
                  <div style={{ background: "#14B8A6", borderRadius: 8, minWidth: 80, display: "flex", alignItems: "center", justifyContent: "center", color: "white", fontSize: 13, fontWeight: 600 }}>
                    Analyze
                  </div>
                </div>
                {["Detecting industry: SaaS / B2B", "ICP: Mid-market Tech Companies", "Region: North America, Europe"].map((item, i) => (
                  <div key={i} style={{ display: "flex", alignItems: "center", gap: 10, padding: "10px 0", borderBottom: "1px solid rgba(255,255,255,0.05)" }}>
                    <div style={{ width: 18, height: 18, borderRadius: "50%", background: "#14B8A6", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 10, color: "white", fontWeight: 700, flexShrink: 0 }}>
                      ✓
                    </div>
                    <span style={{ fontSize: 13, color: "rgba(255,255,255,0.7)" }}>{item}</span>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>

          {/* Step 2 */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: 48, alignItems: "center", marginBottom: 96 }} className="lg:grid-cols-2">
            <motion.div
              initial={{ opacity: 0, x: -40 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              style={{ order: 2 }}
              className="lg:order-1"
            >
              <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                {[
                  { name: "Marcus Webb", title: "VP Sales", company: "Acme Corp", color: "#14B8A6" },
                  { name: "Aisha Patel", title: "Head of Growth", company: "ScaleIO", color: "#F97316" },
                  { name: "Ryan Torres", title: "CEO", company: "Ventures Co", color: "#8B5CF6" },
                ].map((lead, i) => (
                  <motion.div
                    key={lead.name}
                    initial={{ opacity: 0, x: -20 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.1 }}
                    style={{ background: "white", borderRadius: 14, padding: "14px 18px", display: "flex", alignItems: "center", gap: 14, boxShadow: "0 4px 20px rgba(0,0,0,0.07)", border: "1px solid #E2E8F0" }}
                  >
                    <div style={{ width: 42, height: 42, borderRadius: "50%", background: lead.color, display: "flex", alignItems: "center", justifyContent: "center", color: "white", fontWeight: 700, fontSize: 17, flexShrink: 0 }}>
                      {lead.name[0]}
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontWeight: 700, fontSize: 14, color: "#0F172A" }}>{lead.name}</div>
                      <div style={{ fontSize: 12, color: "#64748B" }}>{lead.title} · {lead.company}</div>
                    </div>
                    <div style={{ background: "#14B8A610", border: "1px solid #14B8A628", borderRadius: 20, padding: "3px 10px", fontSize: 11, color: "#14B8A6", fontWeight: 600 }}>
                      ICP ✓
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 40 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              style={{ order: 1 }}
              className="lg:order-2"
            >
              <div style={{ display: "inline-block", background: "linear-gradient(135deg, #F97316, #EA6A00)", borderRadius: 8, padding: "4px 14px", fontSize: 12, fontWeight: 700, color: "white", marginBottom: 18, letterSpacing: "0.04em" }}>
                Step 02
              </div>
              <h3 style={{ fontSize: 28, fontWeight: 800, color: "#0F172A", margin: "0 0 14px 0" }}>Get 5 Free Qualified Leads</h3>
              <p style={{ fontSize: 17, color: "#64748B", lineHeight: 1.7, margin: 0 }}>
                Instantly receive 5 verified decision-makers matched to your ideal customer profile.
              </p>
            </motion.div>
          </div>

          {/* Step 3 */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: 48, alignItems: "center", marginBottom: 96 }} className="lg:grid-cols-2">
            <motion.div
              initial={{ opacity: 0, x: -40 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <div style={{ display: "inline-block", background: "linear-gradient(135deg, #8B5CF6, #7C3AED)", borderRadius: 8, padding: "4px 14px", fontSize: 12, fontWeight: 700, color: "white", marginBottom: 18, letterSpacing: "0.04em" }}>
                Step 03
              </div>
              <h3 style={{ fontSize: 28, fontWeight: 800, color: "#0F172A", margin: "0 0 14px 0" }}>Complete Tasks, Unlock More</h3>
              <p style={{ fontSize: 17, color: "#64748B", lineHeight: 1.7, margin: 0 }}>
                ARIA guides you through setup tasks. Each completed task unlocks more leads and features.
              </p>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 40 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <div style={{ background: "white", borderRadius: 16, padding: 28, boxShadow: "0 20px 60px rgba(0,0,0,0.08)", border: "1px solid #E2E8F0" }}>
                <div style={{ marginBottom: 20 }}>
                  <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 10 }}>
                    <span style={{ fontSize: 14, fontWeight: 600, color: "#0F172A" }}>Setup Progress</span>
                    <span style={{ fontSize: 14, fontWeight: 700, color: "#14B8A6" }}>50%</span>
                  </div>
                  <div style={{ height: 8, background: "#F1F5F9", borderRadius: 4, overflow: "hidden" }}>
                    <motion.div
                      initial={{ width: 0 }}
                      whileInView={{ width: "50%" }}
                      viewport={{ once: true }}
                      transition={{ duration: 1, delay: 0.3 }}
                      style={{ height: "100%", background: "linear-gradient(90deg, #14B8A6, #F97316)", borderRadius: 4 }}
                    />
                  </div>
                </div>
                {[
                  { task: "Connect your website", done: true },
                  { task: "Define your ICP", done: true },
                  { task: "Set up CRM integration", done: false },
                  { task: "Launch first campaign", done: false },
                ].map((t) => (
                  <div key={t.task} style={{ display: "flex", alignItems: "center", gap: 12, padding: "10px 0", borderBottom: "1px solid #F1F5F9" }}>
                    <div style={{ width: 22, height: 22, borderRadius: "50%", background: t.done ? "#14B8A6" : "transparent", border: t.done ? "none" : "2px solid #CBD5E1", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, color: "white", fontWeight: 700, flexShrink: 0 }}>
                      {t.done ? "✓" : ""}
                    </div>
                    <span style={{ fontSize: 14, color: t.done ? "#0F172A" : "#94A3B8", fontWeight: t.done ? 500 : 400 }}>{t.task}</span>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>

          {/* Step 4 */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: 48, alignItems: "center" }} className="lg:grid-cols-2">
            <motion.div
              initial={{ opacity: 0, x: -40 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              style={{ order: 2 }}
              className="lg:order-1"
            >
              <div style={{ background: "#0F1F3D", borderRadius: 16, padding: 28, boxShadow: "0 20px 60px rgba(0,0,0,0.2)" }}>
                {[
                  { label: "ICP Analysis", color: "#14B8A6", width: "90%" },
                  { label: "ABM Strategy", color: "#F97316", width: "75%" },
                  { label: "Outreach Playbook", color: "#8B5CF6", width: "85%" },
                  { label: "Revenue Forecast", color: "#10B981", width: "60%" },
                ].map((item, i) => (
                  <div key={item.label} style={{ marginBottom: 20 }}>
                    <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 6 }}>
                      <span style={{ fontSize: 13, fontWeight: 600, color: "rgba(255,255,255,0.8)" }}>{item.label}</span>
                      <span style={{ fontSize: 12, color: item.color, fontWeight: 700 }}>Complete</span>
                    </div>
                    <div style={{ height: 6, background: "rgba(255,255,255,0.08)", borderRadius: 3 }}>
                      <motion.div
                        initial={{ width: 0 }}
                        whileInView={{ width: item.width }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.8, delay: i * 0.15 }}
                        style={{ height: "100%", background: item.color, borderRadius: 3 }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 40 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              style={{ order: 1 }}
              className="lg:order-2"
            >
              <div style={{ display: "inline-block", background: "linear-gradient(135deg, #10B981, #059669)", borderRadius: 8, padding: "4px 14px", fontSize: 12, fontWeight: 700, color: "white", marginBottom: 18, letterSpacing: "0.04em" }}>
                Step 04
              </div>
              <h3 style={{ fontSize: 28, fontWeight: 800, color: "#0F172A", margin: "0 0 14px 0" }}>Full GTM Strategy Generated</h3>
              <p style={{ fontSize: 17, color: "#64748B", lineHeight: 1.7, margin: 0 }}>
                Get your complete ICP, ABM strategy, and outreach playbooks — ready to execute in 24 hours.
              </p>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          6. SOCIAL PROOF
      ══════════════════════════════════════════════════════════ */}
      <section id="customers" style={{ background: "#0A1628", padding: "6rem 0" }}>
        <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 24px" }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            style={{ textAlign: "center", marginBottom: 64 }}
          >
            <h2 style={{ fontSize: "clamp(28px, 3vw, 36px)", fontWeight: 800, color: "white", margin: 0 }}>
              Loved by Sales Teams Worldwide
            </h2>
          </motion.div>

          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={{ hidden: {}, visible: { transition: { staggerChildren: 0.15 } } }}
            style={{ display: "grid", gridTemplateColumns: "repeat(1, 1fr)", gap: 24 }}
            className="md:grid-cols-3"
          >
            {testimonials.map((t) => (
              <motion.div
                key={t.name}
                variants={{ hidden: { opacity: 0, y: 30 }, visible: { opacity: 1, y: 0 } }}
                style={{
                  background: "rgba(255,255,255,0.05)",
                  backdropFilter: "blur(12px)",
                  WebkitBackdropFilter: "blur(12px)",
                  border: "1px solid rgba(255,255,255,0.1)",
                  borderRadius: 16,
                  padding: "32px",
                }}
              >
                <div style={{ display: "flex", gap: 3, marginBottom: 20 }}>
                  {[1, 2, 3, 4, 5].map((s) => (
                    <span key={s} style={{ color: "#F97316", fontSize: 18 }}>★</span>
                  ))}
                </div>
                <p style={{ fontSize: 15, color: "rgba(255,255,255,0.8)", lineHeight: 1.75, margin: "0 0 24px 0" }}>
                  &ldquo;{t.quote}&rdquo;
                </p>
                <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
                  <div style={{ width: 46, height: 46, borderRadius: "50%", background: t.color, display: "flex", alignItems: "center", justifyContent: "center", color: "white", fontWeight: 700, fontSize: 19, flexShrink: 0 }}>
                    {t.initial}
                  </div>
                  <div>
                    <div style={{ fontWeight: 700, fontSize: 15, color: "white" }}>{t.name}</div>
                    <div style={{ fontSize: 13, color: "rgba(255,255,255,0.45)" }}>{t.role} at {t.company}</div>
                  </div>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          7. INTEGRATIONS
      ══════════════════════════════════════════════════════════ */}
      <section style={{ background: "white", padding: "6rem 0" }}>
        <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 24px" }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            style={{ textAlign: "center", marginBottom: 60 }}
          >
            <h2 style={{ fontSize: "clamp(28px, 3vw, 36px)", fontWeight: 800, color: "#0F172A", margin: 0 }}>
              Works With Your Existing Stack
            </h2>
            <p style={{ fontSize: 18, color: "#64748B", marginTop: 14 }}>
              Connect AVORA with the tools you already use
            </p>
          </motion.div>

          <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 16 }} className="sm:grid-cols-3 md:grid-cols-5">
            {integrations.map((integ, i) => (
              <motion.div
                key={integ.name}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.05, type: "spring", stiffness: 300 }}
                whileHover={{ scale: 1.1, y: -4 }}
                style={{
                  background: "white",
                  border: "1px solid #E2E8F0",
                  borderRadius: 14,
                  padding: "22px 16px",
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  gap: 10,
                  cursor: "pointer",
                  boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
                }}
              >
                <div
                  style={{
                    width: 46,
                    height: 46,
                    borderRadius: 12,
                    background: integ.color,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: "white",
                    fontWeight: 800,
                    fontSize: 14,
                  }}
                >
                  {integ.letter}
                </div>
                <span style={{ fontSize: 13, fontWeight: 600, color: "#475569" }}>{integ.name}</span>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          8. PRICING
      ══════════════════════════════════════════════════════════ */}
      <section id="pricing" style={{ background: "#F8FAFC", padding: "6rem 0" }}>
        <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 24px" }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            style={{ textAlign: "center", marginBottom: 52 }}
          >
            <h2 style={{ fontSize: "clamp(28px, 3vw, 36px)", fontWeight: 800, color: "#0F172A", margin: 0 }}>
              Simple, Transparent Pricing
            </h2>
            <p style={{ fontSize: 18, color: "#64748B", marginTop: 14 }}>Start free, scale as you grow</p>

            {/* Billing toggle */}
            <div
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: 0,
                marginTop: 28,
                background: "white",
                borderRadius: 40,
                padding: 4,
                border: "1px solid #E2E8F0",
                boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
              }}
            >
              <button
                onClick={() => setAnnual(false)}
                style={{
                  padding: "9px 22px",
                  borderRadius: 36,
                  fontSize: 14,
                  fontWeight: 600,
                  background: !annual ? "#14B8A6" : "transparent",
                  color: !annual ? "white" : "#64748B",
                  border: "none",
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}
              >
                Monthly
              </button>
              <button
                onClick={() => setAnnual(true)}
                style={{
                  padding: "9px 22px",
                  borderRadius: 36,
                  fontSize: 14,
                  fontWeight: 600,
                  background: annual ? "#14B8A6" : "transparent",
                  color: annual ? "white" : "#64748B",
                  border: "none",
                  cursor: "pointer",
                  transition: "all 0.2s",
                  display: "flex",
                  alignItems: "center",
                  gap: 8,
                }}
              >
                Annual
                <span style={{ background: "#F97316", color: "white", borderRadius: 20, padding: "2px 8px", fontSize: 11, fontWeight: 700 }}>
                  -20%
                </span>
              </button>
            </div>
          </motion.div>

          <div style={{ display: "grid", gridTemplateColumns: "repeat(1, 1fr)", gap: 24, alignItems: "start" }} className="md:grid-cols-3">
            {pricingPlans.map((plan, i) => (
              <motion.div
                key={plan.name}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1, duration: 0.5 }}
                style={{
                  background: "white",
                  borderRadius: 18,
                  padding: "36px 32px",
                  border: plan.highlight ? "2px solid #14B8A6" : "1px solid #E2E8F0",
                  transform: plan.highlight ? "scale(1.02)" : "none",
                  boxShadow: plan.highlight
                    ? "0 20px 60px rgba(20,184,166,0.15)"
                    : "0 4px 20px rgba(0,0,0,0.05)",
                  position: "relative",
                }}
              >
                {plan.badge && (
                  <div
                    style={{
                      position: "absolute",
                      top: -14,
                      left: "50%",
                      transform: "translateX(-50%)",
                      background: "#14B8A6",
                      color: "white",
                      borderRadius: 20,
                      padding: "5px 18px",
                      fontSize: 12,
                      fontWeight: 700,
                      whiteSpace: "nowrap",
                    }}
                  >
                    {plan.badge}
                  </div>
                )}

                <h3 style={{ fontSize: 22, fontWeight: 800, color: "#0F172A", margin: "0 0 4px 0" }}>{plan.name}</h3>
                <p style={{ fontSize: 13, color: "#64748B", margin: "0 0 22px 0" }}>{plan.for}</p>

                <div style={{ marginBottom: 28 }}>
                  {plan.price === null ? (
                    <span style={{ fontSize: 38, fontWeight: 800, color: "#0F172A" }}>Custom</span>
                  ) : plan.price === 0 ? (
                    <span style={{ fontSize: 38, fontWeight: 800, color: "#0F172A" }}>Free</span>
                  ) : (
                    <div style={{ display: "flex", alignItems: "baseline", gap: 4 }}>
                      <span style={{ fontSize: 38, fontWeight: 800, color: "#0F172A" }}>
                        ${annual ? Math.round((plan.price as number) * 0.8) : plan.price}
                      </span>
                      <span style={{ fontSize: 14, color: "#64748B" }}>/month</span>
                    </div>
                  )}
                </div>

                <ul style={{ listStyle: "none", padding: 0, margin: "0 0 28px 0" }}>
                  {plan.features.map((f) => (
                    <li key={f} style={{ display: "flex", alignItems: "flex-start", gap: 10, marginBottom: 12 }}>
                      <span style={{ color: "#14B8A6", fontSize: 14, fontWeight: 700, flexShrink: 0, lineHeight: "22px" }}>✓</span>
                      <span style={{ fontSize: 14, color: "#475569", lineHeight: 1.5 }}>{f}</span>
                    </li>
                  ))}
                </ul>

                <Link
                  href={plan.href}
                  style={{
                    display: "block",
                    textAlign: "center",
                    padding: "14px",
                    borderRadius: 12,
                    fontWeight: 600,
                    fontSize: 15,
                    textDecoration: "none",
                    transition: "all 0.2s",
                    ...(plan.ctaVariant === "outline-teal"
                      ? { border: "2px solid #14B8A6", color: "#14B8A6", background: "transparent" }
                      : plan.ctaVariant === "coral"
                      ? { background: "#F97316", color: "white", border: "none" }
                      : { background: "#0A1628", color: "white", border: "none" }),
                  }}
                >
                  {plan.cta}
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          9. FINAL CTA
      ══════════════════════════════════════════════════════════ */}
      <section
        style={{
          background: "linear-gradient(135deg, #0D9488 0%, #14B8A6 50%, #0D3D3D 100%)",
          backgroundSize: "200% 200%",
          animation: "gradientShift 8s ease infinite",
          padding: "6rem 0",
          position: "relative",
          overflow: "hidden",
        }}
      >
        <div
          style={{
            position: "absolute",
            top: "-50%",
            left: "-10%",
            width: 500,
            height: 500,
            borderRadius: "50%",
            background: "rgba(255,255,255,0.05)",
            pointerEvents: "none",
          }}
        />
        <div style={{ maxWidth: 860, margin: "0 auto", padding: "0 24px", textAlign: "center", position: "relative", zIndex: 10 }}>
          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            style={{ fontSize: "clamp(32px, 4vw, 48px)", fontWeight: 800, color: "white", margin: 0 }}
          >
            Ready to Fill Your Pipeline?
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2, duration: 0.6 }}
            style={{ fontSize: 18, color: "rgba(255,255,255,0.85)", marginTop: 18, marginBottom: 44, lineHeight: 1.6 }}
          >
            Join 2,000+ sales teams using AVORA to find and close more deals.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.35, duration: 0.6 }}
            style={{ display: "flex", flexWrap: "wrap", gap: 16, justifyContent: "center" }}
          >
            <Link
              href="/register"
              style={{
                display: "inline-flex",
                alignItems: "center",
                background: "white",
                color: "#0D9488",
                fontWeight: 700,
                fontSize: 15,
                padding: "16px 28px",
                borderRadius: 14,
                textDecoration: "none",
                boxShadow: "0 8px 32px rgba(0,0,0,0.15)",
                transition: "transform 0.2s",
              }}
            >
              Start for Free — No Credit Card Required
            </Link>
            <Link
              href="/contact"
              style={{
                display: "inline-flex",
                alignItems: "center",
                background: "transparent",
                color: "white",
                fontWeight: 600,
                fontSize: 15,
                padding: "16px 28px",
                borderRadius: 14,
                textDecoration: "none",
                border: "2px solid rgba(255,255,255,0.45)",
                transition: "background 0.2s",
              }}
            >
              Talk to Sales
            </Link>
          </motion.div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════
          10. FOOTER
      ══════════════════════════════════════════════════════════ */}
      <footer style={{ background: "#0A1628", padding: "5rem 0 2rem" }}>
        <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 24px" }}>
          {/* Grid: brand + 4 columns */}
          <div
            style={{ display: "grid", gridTemplateColumns: "repeat(1, 1fr)", gap: "3rem 2rem", paddingBottom: 48, borderBottom: "1px solid rgba(255,255,255,0.07)" }}
            className="md:grid-cols-5"
          >
            {/* Brand column */}
            <div>
              <AvoraLogo variant="light" height={38} />
              <p style={{ fontSize: 13, color: "rgba(255,255,255,0.38)", marginTop: 14, lineHeight: 1.7, maxWidth: 200 }}>
                AI-Powered GTM &amp; Sales Intelligence
              </p>
            </div>

            {/* Link columns */}
            {footerColumns.map((col) => (
              <div key={col.title}>
                <h4
                  style={{
                    fontSize: 12,
                    fontWeight: 700,
                    color: "rgba(255,255,255,0.85)",
                    marginBottom: 20,
                    textTransform: "uppercase",
                    letterSpacing: "0.08em",
                    margin: "0 0 18px 0",
                  }}
                >
                  {col.title}
                </h4>
                <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
                  {col.links.map((link) => (
                    <li key={link} style={{ marginBottom: 10 }}>
                      <Link
                        href="#"
                        style={{ fontSize: 14, color: "rgba(255,255,255,0.42)", textDecoration: "none", transition: "color 0.2s" }}
                        className="hover:text-[#14B8A6]"
                      >
                        {link}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          {/* Bottom bar */}
          <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 16, paddingTop: 32 }}>
            <p style={{ fontSize: 13, color: "rgba(255,255,255,0.32)", margin: 0 }}>
              © 2026 AVORA by Enigma Sales. All rights reserved.
            </p>
            <div style={{ display: "flex", gap: 20 }}>
              {/* LinkedIn */}
              <a href="#" aria-label="LinkedIn" style={{ color: "rgba(255,255,255,0.38)", transition: "color 0.2s" }} className="hover:text-[#14B8A6]">
                <svg width="20" height="20" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6zM2 9h4v12H2z" />
                  <circle cx="4" cy="4" r="2" />
                </svg>
              </a>
              {/* X / Twitter */}
              <a href="#" aria-label="Twitter" style={{ color: "rgba(255,255,255,0.38)", transition: "color 0.2s" }} className="hover:text-[#14B8A6]">
                <svg width="20" height="20" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
                </svg>
              </a>
              {/* YouTube */}
              <a href="#" aria-label="YouTube" style={{ color: "rgba(255,255,255,0.38)", transition: "color 0.2s" }} className="hover:text-[#14B8A6]">
                <svg width="20" height="20" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M22.54 6.42a2.78 2.78 0 0 0-1.95-1.96C18.88 4 12 4 12 4s-6.88 0-8.59.46a2.78 2.78 0 0 0-1.95 1.96A29 29 0 0 0 1 12a29 29 0 0 0 .46 5.58A2.78 2.78 0 0 0 3.41 19.6C5.12 20 12 20 12 20s6.88 0 8.59-.46a2.78 2.78 0 0 0 1.95-1.95A29 29 0 0 0 23 12a29 29 0 0 0-.46-5.58zM9.75 15.02V8.98L15.5 12l-5.75 3.02z" />
                </svg>
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
